//! Fix engine types.
//!
//! Defines the data model for planned fixes: text edits grouped by file,
//! with support for pattern-based (deterministic) and LLM-assisted fixes.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// A single text replacement within a file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextEdit {
    /// 1-indexed line number where the edit applies.
    pub line: u32,
    /// The original text to find on this line.
    pub old_text: String,
    /// The replacement text.
    pub new_text: String,
    /// Rule ID that generated this fix.
    pub rule_id: String,
    /// Human-readable description of what this fix does.
    pub description: String,
}

/// How confident we are in a fix.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FixConfidence {
    /// Mechanical rename/removal — always correct.
    Exact,
    /// Pattern-based but may need manual review.
    High,
    /// LLM-generated — needs review.
    Medium,
    /// Best-effort suggestion only.
    Low,
}

/// How the fix was generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FixSource {
    /// Deterministic pattern-based transform.
    Pattern,
    /// Generated by LLM.
    Llm,
    /// Manual fix required — we can only flag it.
    Manual,
}

/// A planned fix for a single incident.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedFix {
    /// The text edits to apply.
    pub edits: Vec<TextEdit>,
    /// Confidence level.
    pub confidence: FixConfidence,
    /// How the fix was generated.
    pub source: FixSource,
    /// The rule ID this fix addresses.
    pub rule_id: String,
    /// File URI from the incident.
    pub file_uri: String,
    /// Line number from the incident.
    pub line: u32,
    /// Description of what this fix does.
    pub description: String,
}

/// A fix plan: all planned fixes grouped by file.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FixPlan {
    /// Fixes grouped by file path.
    pub files: BTreeMap<PathBuf, Vec<PlannedFix>>,
    /// Incidents that could not be auto-fixed and need manual attention.
    pub manual: Vec<ManualFixItem>,
    /// Incidents pending LLM-assisted fix.
    pub pending_llm: Vec<LlmFixRequest>,
}

/// An incident that requires manual fixing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManualFixItem {
    pub rule_id: String,
    pub file_uri: String,
    pub line: u32,
    pub message: String,
    pub code_snip: Option<String>,
}

/// A request to send to the LLM for fix generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmFixRequest {
    pub rule_id: String,
    pub file_uri: String,
    pub file_path: PathBuf,
    pub line: u32,
    pub message: String,
    pub code_snip: Option<String>,
    /// The full source content of the file (for context).
    pub source: Option<String>,
}

/// Result of applying a fix plan.
#[derive(Debug, Default)]
pub struct FixResult {
    /// Number of files modified.
    pub files_modified: usize,
    /// Number of edits applied.
    pub edits_applied: usize,
    /// Number of edits skipped (already applied or conflict).
    pub edits_skipped: usize,
    /// Errors encountered.
    pub errors: Vec<String>,
}

/// A rename mapping: old name -> new name.
/// Used for prop renames, component renames, import renames, etc.
#[derive(Debug, Clone)]
pub struct RenameMapping {
    pub old: String,
    pub new: String,
}

/// Known fix strategies keyed by rule ID.
/// Each entry defines how to transform incidents from that rule into text edits.
#[derive(Debug, Clone)]
pub enum FixStrategy {
    /// Simple text replacement: rename the matched text.
    /// The mapping is propName/componentName/importedName old -> new.
    Rename(Vec<RenameMapping>),
    /// Remove the matched prop (delete the entire attribute from the JSX tag).
    RemoveProp,
    /// Replace an import source path.
    ImportPathChange { old_path: String, new_path: String },
    /// Replace a CSS variable/class prefix.
    CssVariablePrefix {
        old_prefix: String,
        new_prefix: String,
    },
    /// Update a dependency version in package.json.
    UpdateDependency {
        package: String,
        new_version: String,
    },
    /// No auto-fix available — flag for manual review.
    Manual,
    /// Send to LLM for fix generation.
    Llm,
}

/// A single mapping entry within a consolidated strategy.
#[derive(Debug, Clone, Deserialize)]
pub struct MappingEntry {
    #[serde(default)]
    pub from: Option<String>,
    #[serde(default)]
    pub to: Option<String>,
    #[serde(default)]
    pub component: Option<String>,
    #[serde(default)]
    pub prop: Option<String>,
}

/// JSON-serializable strategy entry from `fix-strategies.json`.
///
/// For single-rule strategies, `from`/`to` hold the mapping.
/// For consolidated rules, `mappings` holds all individual mappings from
/// the merged rules, allowing the fix engine to apply all renames/removals.
///
/// ```json
/// { "strategy": "Rename", "from": "Chip", "to": "Label",
///   "mappings": [
///     {"from": "Chip", "to": "Label"},
///     {"from": "ChipGroup", "to": "LabelGroup"}
///   ]
/// }
/// ```
#[derive(Debug, Clone, Deserialize)]
pub struct StrategyEntry {
    pub strategy: String,
    #[serde(default)]
    pub from: Option<String>,
    #[serde(default)]
    pub to: Option<String>,
    #[serde(default)]
    pub component: Option<String>,
    #[serde(default)]
    pub prop: Option<String>,
    /// npm package name (for UpdateDependency strategy).
    #[serde(default)]
    pub package: Option<String>,
    /// New version range to set (for UpdateDependency strategy).
    #[serde(default)]
    pub new_version: Option<String>,
    /// All individual mappings for consolidated rules.
    #[serde(default)]
    pub mappings: Vec<MappingEntry>,
}

impl StrategyEntry {
    /// Convert a JSON strategy entry to a `FixStrategy`.
    ///
    /// When `mappings` is populated (consolidated rule), builds a multi-mapping
    /// `FixStrategy::Rename` or extracts multiple `RemoveProp` targets.
    pub fn to_fix_strategy(&self) -> FixStrategy {
        match self.strategy.as_str() {
            "Rename" => {
                let mut renames: Vec<RenameMapping> = Vec::new();
                // Collect from mappings array (consolidated rule)
                for m in &self.mappings {
                    if let (Some(from), Some(to)) = (&m.from, &m.to) {
                        renames.push(RenameMapping {
                            old: from.clone(),
                            new: to.clone(),
                        });
                    }
                }
                // Fall back to top-level from/to (single-rule strategy)
                if renames.is_empty() {
                    if let (Some(from), Some(to)) = (&self.from, &self.to) {
                        renames.push(RenameMapping {
                            old: from.clone(),
                            new: to.clone(),
                        });
                    }
                }
                if renames.is_empty() {
                    FixStrategy::Manual
                } else {
                    FixStrategy::Rename(renames)
                }
            }
            "RemoveProp" => FixStrategy::RemoveProp,
            "CssVariablePrefix" => {
                if let (Some(from), Some(to)) = (&self.from, &self.to) {
                    FixStrategy::CssVariablePrefix {
                        old_prefix: from.clone(),
                        new_prefix: to.clone(),
                    }
                } else {
                    FixStrategy::Manual
                }
            }
            "ImportPathChange" => {
                if let (Some(from), Some(to)) = (&self.from, &self.to) {
                    FixStrategy::ImportPathChange {
                        old_path: from.clone(),
                        new_path: to.clone(),
                    }
                } else {
                    FixStrategy::Manual
                }
            }
            "UpdateDependency" => {
                if let (Some(package), Some(new_version)) = (&self.package, &self.new_version) {
                    FixStrategy::UpdateDependency {
                        package: package.clone(),
                        new_version: new_version.clone(),
                    }
                } else {
                    FixStrategy::Manual
                }
            }
            "PropValueChange" | "PropTypeChange" => FixStrategy::Llm,
            "LlmAssisted" => FixStrategy::Llm,
            _ => FixStrategy::Manual,
        }
    }
}

/// Load fix strategies from a JSON file.
///
/// Returns a map of rule_id -> FixStrategy.
pub fn load_strategies_from_json(
    path: &Path,
) -> Result<BTreeMap<String, FixStrategy>, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let entries: BTreeMap<String, StrategyEntry> = serde_json::from_str(&content)?;
    let strategies = entries
        .into_iter()
        .map(|(rule_id, entry)| (rule_id, entry.to_fix_strategy()))
        .collect();
    Ok(strategies)
}
